USE [master]
GO

/****** Object:  Database [TallerDB]    Script Date: 5/6/2017 22:52:50 ******/
CREATE DATABASE [TallerDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TallerDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\TallerDB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TallerDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\TallerDB_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TallerDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TallerDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TallerDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TallerDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TallerDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TallerDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TallerDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TallerDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TallerDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TallerDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TallerDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TallerDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TallerDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TallerDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TallerDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TallerDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TallerDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TallerDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TallerDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TallerDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TallerDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TallerDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TallerDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TallerDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TallerDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TallerDB] SET  MULTI_USER 
GO

ALTER DATABASE [TallerDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TallerDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TallerDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TallerDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TallerDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TallerDB] SET  READ_WRITE 
GO

